name: vasp-rag

channels:
  - conda-forge
  - pytorch

dependencies:
  - python=3.11

  - pip
  - numpy
  - pandas
  - tqdm
  - requests

  - pytorch
  - cpuonly

  - pip:
      - elasticsearch==8.11.0
      - google-cloud-aiplatform
      - transformers==4.45.0
      - FlagEmbedding==1.2.10
      - sentence-transformers
      - langchain
      - langgraph
      - python-dotenv
      - beautifulsoup4
      - lxml
      - fastapi
      - uvicorn
      - pydantic
      - tiktoken
      - tavily-python